version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: appreciate_backend_wiremock
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
      # note --global-response-templating switch turns on use of handlebars templating in wiremock (and avoids need to specify this on a per request basis) 
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - 8080:8080
