version: "3"
services:
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: appreciate_backend_wiremock
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    ports:
      - 8080:8080
  #   for endpoints
  # - https://app.buymeacoffee.com/api/v1/check_availability
